// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qroqxvfbtsjypvibywqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyb3F4dmZidHNqeXB2aWJ5d3FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNTY2MTksImV4cCI6MjA3MzgzMjYxOX0.kLEwJ0C3wPwe832bPXi3Rw4fIwyhnhMnPbwoHvGIiw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});
